import { NextRequest, NextResponse } from 'next/server';
import { createServiceClient } from '@/lib/supabase/server';

// ── DB-backed, expiring shared-link store ────────────────────────────────────
// Previously this lived in an in-process `Map`, which — as the original
// comment here noted — gets wiped on every serverless cold start and isn't
// shared across instances on Vercel. Now it's a real table (see
// supabase/schema.sql: shared_links), so a link generated by one invocation
// is readable by any other, and survives redeploys until it expires.
//
// Uses the service-role client so it works regardless of whether the caller
// has a session — HR is authenticated when creating a link, but the manager
// reading it deliberately isn't (see FR-10 / middleware.ts).

const TTL_MS = 24 * 60 * 60 * 1000; // 24 hours

export async function POST(req: NextRequest) {
  const body = await req.json().catch(() => null);
  if (!body || !Array.isArray(body.records)) {
    return NextResponse.json({ error: 'records array required' }, { status: 400 });
  }

  const supabase = createServiceClient();
  const expiresAt = new Date(Date.now() + TTL_MS).toISOString();
  const { data, error } = await supabase
    .from('shared_links')
    .insert({ data: body.records, expires_at: expiresAt })
    .select('token')
    .single();

  if (error || !data) {
    return NextResponse.json({ error: 'Failed to create shared link' }, { status: 500 });
  }

  return NextResponse.json({ token: data.token, expiresAt });
}

export async function GET(req: NextRequest) {
  const token = req.nextUrl.searchParams.get('token');
  if (!token) {
    return NextResponse.json({ error: 'token required' }, { status: 400 });
  }

  const supabase = createServiceClient();
  const { data } = await supabase
    .from('shared_links')
    .select('data, expires_at')
    .eq('token', token)
    .maybeSingle();

  if (!data || new Date(data.expires_at).getTime() <= Date.now()) {
    return NextResponse.json({ error: 'not found or expired' }, { status: 404 });
  }

  return NextResponse.json({ records: data.data });
}
